### ISSUE TITLE
Example doesn't cover all record types

### ISSUE THREAD

**Issue by isaacwalkercox** [matteofabbri/netfluid.dns#1]
I am trying to test this DNS library with sending an A record in response to a request. The Example folder doesn't help me. Please update it.

Thank you

**Comment by matteofabbri** [comment]
tnx, working on it.
Btw, to create any record all you got to do is to fill all the fields, int this case the A,B,C,D bytes.
Example, if the IP is 127.0.0.1:

            new RecordA()
            {
                Name = "www.mydomain.org",
                A = 127,
                B = 0,
                C = 0,
                D = 1
            };

There is also an helper:

var record = RecordA.Parse("127.0.0.1");

**Comment by isaacwalkercox** [comment]
Thanks. Can you help with one other thing?

⁣Sent from TypeApp ​

**Comment by isaacwalkercox** [comment]
Thank you.

**Comment by matteofabbri** [comment]
example improved, as the same of socket handling.
let known how does ti works.
other improvements are coming :)

**Comment by isaacwalkercox** [comment]
Thank you 😊
